main:
  push:
    - branches:
        - main
        - jsDelivr
      services:
        - docker
      imports:
        - https://cnb.cool/xiyingruyi/Secrets/-/blob/main/env.yml
      stages:
        - name: Git Push to GitHub
          image: ubuntu:latest
          environment:
            - GIT_ACCESS_TOKEN
            - GIT_USERNAME
          script: |
            echo "Pipeline 开始执行，采用原生 Git 推送..."
            
            # 1. 密钥检查
            if [ -z "$GIT_ACCESS_TOKEN" ]; then echo "错误: GIT_ACCESS_TOKEN 未设置！"; exit 1; fi
            if [ -z "$GIT_USERNAME" ]; then GIT_USERNAME="xiyingruyi"; fi
            echo "密钥检查通过。"
            
            # 2. 安装 Git
            apt update
            apt install -y git
            
            # 3. 配置 Git 用户信息
            git config --global user.email "ci-bot@cnb.cool"
            git config --global user.name "$GIT_USERNAME"
            
            # 4. 动态获取当前分支
            CURRENT_BRANCH=$(git branch --show-current)
            echo "当前分支: $CURRENT_BRANCH"

            # 5. 避免无限循环的逻辑
            REMOTE_URL="https://${GIT_USERNAME}:${GIT_ACCESS_TOKEN}@github.com/xiyingruyi/Stash-rules.git"
            git remote add github $REMOTE_URL || git remote set-url github $REMOTE_URL
            git fetch github --no-tags
            
            COMMITS_AHEAD=$(git rev-list --count github/$CURRENT_BRANCH..$CURRENT_BRANCH 2>/dev/null || echo 0)
            if [ $COMMITS_AHEAD -eq 0 ]; then 
                echo "无变更需要同步（本地仓库已一致）。"; 
                exit 0; 
            fi
            echo "领先 $COMMITS_AHEAD commits，正在同步到 GitHub..."

            # 6. 稳健推送
            echo "尝试 pull GitHub 变更..."
            if git pull github $CURRENT_BRANCH; then
              echo "Pull 成功。"
            else
              echo "Pull 失败，继续 force-with-lease。"
            fi
            git push github $CURRENT_BRANCH --force-with-lease

            if [ $? -eq 0 ]; then
                echo "Git 推送成功！ (auto-sync from CNB)"
            else
                echo "Git 推送失败！"
                exit 1
            fi
          timeout: 10m