push:
  - branches:
      - main  # 具体名，无 *
    services:
      - docker
    imports:
      - https://cnb.cool/xiyingruyi/Secrets/-/blob/main/env.yml  # blob；若 404，用 /raw/main/env.yml
    stages:
      - name: Git Push to GitHub
        image: ubuntu:latest
        environment:
          - GIT_ACCESS_TOKEN
          - GIT_USERNAME
        script: |
          echo "Pipeline 开始执行..."
          if [ -z "$GIT_ACCESS_TOKEN" ]; then echo "错误: Token 未设置"; exit 1; fi
          echo "密钥检查通过。"
          # ... 您的完整脚本（安装 git、fetch、比较、push 等）
        timeout: 10m