name: Auto Purge jsDelivr Cache  # 工作流名称，在 Actions 页显示

on:
  push:  # 触发条件：每次 push 到指定分支时运行
    branches: [ main, jsDelivr ]  # 支持多个分支：替换为你的，如 [ main, dev, feature ] 

jobs:
  purge:
    runs-on: ubuntu-latest  # 运行环境：Linux 虚拟机
    steps:
      - name: Checkout code  # 第一步：拉取最新代码（必须，用于 git diff）
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 拉取最近 2 个 commit，便于 diff

      - name: Detect Changes and Purge Cache  # 第二步：检测变化并动态 purge
        run: |
          # 获取最近 push 的变化文件列表（排除 .github/workflows/ 等无关）
          CHANGED_FILES=$(git diff --name-only HEAD~1 | grep -v '^.github/workflows/' || true)
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No relevant files changed, skipping purge."
            exit 0
          fi
          
          echo "Changed files: $CHANGED_FILES"
          
          # 循环每个变化文件，生成并 purge URL
          for file in $CHANGED_FILES; do
            if [[ "$file" == *.* ]]; then  # 只处理有扩展名的文件（如 .js、.css）
              REPO="${{ github.repository }}"  # 动态获取 user/repo
              BRANCH="${{ github.ref_name }}"  # 动态获取分支，如 main 或 dev
              
              # 生成三个 CDN URL（用于日志显示）
              CDN1_URL="https://fastly.jsdelivr.net/gh/$REPO@$BRANCH/$file"
              CDN2_URL="https://cdn.jsdmirror.com/gh/$REPO@$BRANCH/$file"
              CDN3_URL="https://cdn.jsdelivr.net/gh/$REPO@$BRANCH/$file"
              
              echo "Changed file: $file"
              echo "URLs: $CDN1_URL | $CDN2_URL | $CDN3_URL"
              
              # Purge jsDelivr (覆盖 fastly 和 cdn.jsdelivr.net)
              PURGE_JSDELIVR="https://purge.jsdelivr.net/gh/$REPO@$BRANCH/$file"
              echo "Purging jsDelivr (fastly & cdn.jsdelivr.net): $PURGE_JSDELIVR"
              RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null "$PURGE_JSDELIVR")
              
              if [ "$RESPONSE" = "200" ]; then
                echo "✅ Purged jsDelivr successfully (fastly & cdn.jsdelivr.net): $CDN1_URL, $CDN3_URL"
              else
                echo "❌ Purge failed for jsDelivr (code $RESPONSE): $CDN1_URL, $CDN3_URL"
              fi
              
              # jsdmirror: 无官方 purge API，跳过并提示手动处理
              echo "ℹ️ For cdn.jsdmirror.com ($CDN2_URL): No auto-purge available. Wait for sync (~hours) or manual contact jsdmirror."
            fi
          done
