name: Sync to CNB - All Branches

on:
  push:
    branches:
      - '**'  # 匹配所有分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取所有历史和分支

      - name: Sync to CNB Repository
        run: |
          CURRENT_BRANCH_NAME="${{ github.ref_name }}"
          echo "检查分支: $CURRENT_BRANCH_NAME 到 CNB..."

          git remote add cnb https://cnb.cool/xiyingruyi/Stash-rules.git || true
          git fetch cnb --no-tags

          commits_ahead=$(git rev-list --count cnb/$CURRENT_BRANCH_NAME..$CURRENT_BRANCH_NAME 2>/dev/null || echo 0)
          if [ $commits_ahead -eq 0 ]; then
            echo "无变更，跳过（防循环）。"
            exit 0
          fi

          echo "领先 $commits_ahead commits，同步中..."

          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/xiyingruyi/Stash-rules.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="xiyingruyi" \
            -e PLUGIN_PASSWORD="${{ secrets.CNB }}" \
            -e PLUGIN_BRANCH="$CURRENT_BRANCH_NAME" \
            -e PLUGIN_FORCE="false" \
            -e PLUGIN_PUSH_TAGS="false" \
            tencentcom/git-sync

          echo "同步完成！"
