name: Sync to CNB

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完整历史，便于 force push

      - name: Check sync source
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ $COMMIT_MSG == [sync-from-cnb]* ]]; then
            echo "Skip sync: from CNB"
            exit 0
          fi
          echo "Proceed to sync to CNB"

      - name: Sync to CNB
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/xiyingruyi/Stash-rules.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="xiyingruyi" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB_TOKEN }} \
            -e PLUGIN_BRANCH="main" \
            -e PLUGIN_FORCE="true" \
            -e PLUGIN_PUSH_TAGS="true" \
            -e PLUGIN_SYNC_MODE="push" \
            -e PLUGIN_GIT_USER="GitHub Sync Bot" \
            -e PLUGIN_GIT_EMAIL="sync-bot@github.com" \
            tencentcom/git-sync
