name: Sync to CNB

on:
  push:
    branches: ['*']  # 全部分支触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史

      - name: Add CNB Remote and Fetch
        run: |
          git remote add cnb https://xiyingruyi:${{ secrets.CNB_TOKEN }}@cnb.cool/xiyingruyi/Stash-rules.git || true
          git fetch cnb '+refs/heads/*:refs/remotes/cnb/*'

      - name: Sync All Branches
        run: |
          # 获取共同分支列表（去重）
          GITHUB_BRANCHES=$(git ls-remote --heads origin | sed 's#^.*refs/heads/##')
          CNB_BRANCHES=$(git ls-remote --heads cnb | sed 's#^.*refs/heads/##')
          COMMON_BRANCHES=$(comm -12 <(echo "$GITHUB_BRANCHES" | sort) <(echo "$CNB_BRANCHES" | sort))
          
          SYNC_COUNT=0
          while IFS= read -r BRANCH; do
            if [ -z "$BRANCH" ]; then continue; fi
            
            # 获取时间戳
            GITHUB_TIME=$(git log -1 --format=%ct refs/remotes/origin/$BRANCH 2>/dev/null || echo 0)
            CNB_TIME=$(git log -1 --format=%ct refs/remotes/cnb/$BRANCH 2>/dev/null || echo 0)
            
            echo "分支 '$BRANCH': GitHub $GITHUB_TIME, CNB $CNB_TIME"
            
            if [ $GITHUB_TIME -gt $CNB_TIME ]; then
              echo "GitHub 覆盖 CNB ($BRANCH)"
              git push cnb $BRANCH:$BRANCH
              ((SYNC_COUNT++))
            elif [ $CNB_TIME -gt $GITHUB_TIME ]; then
              echo "跳过：CNB 较新 ($BRANCH)"
            else
              echo "时间戳相同 ($BRANCH)"
            fi
          done <<< "$COMMON_BRANCHES"
          
          echo "更新 $SYNC_COUNT 个分支"
        env:
          GIT_USERNAME: ${{ github.actor }}
          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com

      - name: Optional Sync Tags
        run: git push cnb --tags
