name: Sync to CNB

# 当代码推送到任何分支时触发同步
on: 
  push:
    branches:
      - '**' # 匹配所有分支的推送操作

jobs:
  sync:
    # 确保只在 GitHub 的主仓库运行（防止同步循环）
    if: github.repository == 'xiyingruyi/Stash-rules'
    runs-on: ubuntu-latest
    
    steps:
      # 步骤 1: 检查代码到工作区
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 步骤 2: 使用 Git Sync 插件推送到 CNB
      - name: Push to CNB Repository
        run: |
          # 请特别注意，每一行末尾的 \ 后面都没有空格！
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/xiyingruyi/Stash-rules.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB }} \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
