name: Sync to CNB

on:
  push:
    branches:
      - '**'  # 所有分支

jobs:
  sync:
    # 只在指定仓库运行（替换为你的仓库名）
    if: github.repository == 'xiyingruyi/Stash-rules'  # 对于其他仓库，替换 repo 名
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完整历史

      - name: Sync to CNB
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/xiyingruyi/Stash-rules.git" \  # 替换 repo 名
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="xiyingruyi" \  # 你的 CNB 用户名
            -e PLUGIN_PASSWORD=${{ secrets.CNB_TOKEN }} \  # CNB Token secret
            -e PLUGIN_FORCE="true" \  # 强制覆盖
            -e PLUGIN_SYNC_MODE="push" \
            -e PLUGIN_PUSH_TAGS="true" \
            tencentcom/git-sync
          echo "Synced to CNB successfully"
