name: Sync to CNB - All Branches

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to CNB Repository
        run: |
          CURRENT_BRANCH_NAME="${{ github.ref_name }}"
          echo "检查分支: $CURRENT_BRANCH_NAME"

          # 设置 Git 用户
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 添加 CNB 远程
          git remote add cnb https://cnb.cool/xiyingruyi/Stash-rules.git || git remote set-url cnb https://cnb.cool/xiyingruyi/Stash-rules.git
          git fetch cnb --no-tags

          # 获取时间戳（Unix 秒）
          GITHUB_TIME=$(git log -1 --format=%ct $CURRENT_BRANCH_NAME)
          CNB_TIME=$(git log -1 --format=%ct cnb/$CURRENT_BRANCH_NAME 2>/dev/null || echo 0)

          echo "GitHub last commit time: $GITHUB_TIME"
          echo "CNB last commit time: $CNB_TIME"

          # 如果 GitHub 不新，skip
          if [ $GITHUB_TIME -le $CNB_TIME ]; then
            echo "CNB 更新或一致，跳过推送。"
            exit 0
          fi

          echo "GitHub 新，推送 $((GITHUB_TIME - CNB_TIME)) 秒的变更到 CNB..."

          # 注入 token
          if [ -z "${{ secrets.CNB }}" ]; then
            echo "错误: CNB token 未设置！"
            exit 1
          fi
          git config --global url."https://xiyingruyi:${{ secrets.CNB }}@cnb.cool/".insteadOf "https://cnb.cool/"

          # 直接 push（无 rebase，简单）
          git push cnb $CURRENT_BRANCH_NAME

          if [ $? -eq 0 ]; then
            echo "同步成功！"
          else
            echo "推送失败！"
            exit 1
          fi

          # 清理
          git config --global --unset url."https://xiyingruyi:${{ secrets.CNB }}@cnb.cool/".insteadOf
        env:
          CNB_TOKEN: ${{ secrets.CNB }}
