name: Sync to CNB

# 当代码推送到任何分支时触发同步
on:
  push:
    branches:
      - '**' # 匹配所有分支的推送操作

jobs:
  sync:
    # 步骤 1: 【防止循环】检查是否为 CNB 同步机器人推送的提交。
    # 
    # 务必将 'cnb-sync-bot' 替换为你实际用于 CNB 同步的 GitHub 用户名/机器人名（即 PAT 或密钥关联的用户名）。
    # 如果是该用户名推送的，则跳过本次同步到 CNB 的操作，防止无限循环。
    if: github.repository == 'xiyingruyi/Stash-rules' && github.actor != 'cnb-sync-bot'

    runs-on: ubuntu-latest
    
    steps:
      # 步骤 1: 检查代码到工作区
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录

      # 步骤 2: 使用 Git Sync 插件推送到 CNB
      - name: Push to CNB Repository
        run: |
          # 请特别注意，每一行末尾的 \ 后面都没有空格！
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/xiyingruyi/Stash-rules.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB }} \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
