name: Sync to CNB - All Branches

on:
  push:
    branches:
      - '**'  # 匹配所有分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取所有历史和分支

      - name: Sync to CNB Repository
        run: |
          # 获取当前分支名称
          CURRENT_BRANCH_NAME="${{ github.ref_name }}"
          echo "检查当前分支: $CURRENT_BRANCH_NAME 是否需要同步到 CNB..."

          # 添加 CNB 远程仓库（不带凭证，避免暴露）
          git remote add cnb https://cnb.cool/xiyingruyi/Stash-rules.git || git remote set-url cnb https://cnb.cool/xiyingruyi/Stash-rules.git
          git fetch cnb --no-tags

          # 检查当前分支是否领先于 CNB（避免循环）
          commits_ahead=$(git rev-list --count cnb/$CURRENT_BRANCH_NAME..$CURRENT_BRANCH_NAME 2>/dev/null || echo 0)
          if [ $commits_ahead -eq 0 ]; then
            echo "无变更需要同步（仓库已一致或分支不存在）。"
            exit 0
          fi

          echo "当前分支领先 $commits_ahead 个 commits，正在同步到 CNB..."

          # 安全注入 CNB token（从 Secrets 加载，避免 URL 嵌入）
          if [ -z "${{ secrets.CNB }}" ]; then
            echo "错误: CNB token 未设置！请在 GitHub Secrets 中添加 CNB。"
            exit 1
          fi
          git config --global url."https://xiyingruyi:${{ secrets.CNB }}@cnb.cool/".insteadOf "https://cnb.cool/"

          # 新增：合并 CNB 远程变更（防 non-fast-forward 拒绝）
          echo "合并远程变更以确保 fast-forward..."
          if ! git merge-base --is-ancestor cnb/$CURRENT_BRANCH_NAME $CURRENT_BRANCH_NAME; then
            git pull cnb $CURRENT_BRANCH_NAME --rebase
            if [ $? -ne 0 ]; then
              echo "合并失败：冲突需手动解决。"
              exit 1
            fi
            echo "远程变更已 rebase 整合。"
          else
            echo "本地已是最新的，无需 pull。"
          fi

          # 重新检查领先 commits（合并后）
          commits_ahead=$(git rev-list --count cnb/$CURRENT_BRANCH_NAME..$CURRENT_BRANCH_NAME 2>/dev/null || echo 0)
          if [ $commits_ahead -eq 0 ]; then
            echo "合并后无变更需要同步。"
            exit 0
          fi

          # 执行推送（使用 --force-with-lease 安全 force，如果 rebase 后仍需）
          git push cnb $CURRENT_BRANCH_NAME --force-with-lease

          if [ $? -eq 0 ]; then
            echo "同步到 CNB 成功！"
          else
            echo "同步失败！"
            exit 1
          fi

          # 清理临时 Git 配置
          git config --global --unset url."https://xiyingruyi:${{ secrets.CNB }}@cnb.cool/".insteadOf
        env:
          CNB_TOKEN: ${{ secrets.CNB }}  # 可选：额外环境变量，便于调试
