name: Sync to CNB - All Branches

on:
  push:
    # 匹配所有分支的推送事件，不限制 specific branches
    # ⚠️ 注意：这也会在创建新分支时触发
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出 GitHub 仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 确保拉取所有历史记录
          fetch-depth: 0
          # 确保拉取所有分支（通常不需要显式设置，但为了安全可以加上）
          # fetch-depth: 0 已经包含了所有历史和分支信息

      # 2. 同步到 CNB 仓库
      - name: Sync to CNB Repository
        run: |
          # 获取当前触发工作流的分支名称
          CURRENT_BRANCH_NAME="${{ github.ref_name }}"
          echo "同步当前分支: $CURRENT_BRANCH_NAME 到 cnb.cool..."
          
          # 运行 git-sync Docker 镜像进行同步
          # PLUGIN_BRANCH 设置为 CURRENT_BRANCH_NAME，确保推送到同名分支
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/xiyingruyi/Stash-rules.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="xiyingruyi" \
            -e PLUGIN_PASSWORD="${{ secrets.CNB }}" \
            -e PLUGIN_BRANCH="$CURRENT_BRANCH_NAME" \
            tencentcom/git-sync
        env:
          # 引用你的 Secret 名称 CNB
          CNB_ACCESS_TOKEN: ${{ secrets.CNB }}
