      # 新增：预拉取 CNB 变化并 merge（替换原 Push 步骤前）
      - name: Pre-merge with CNB
        if: steps.check_sync.outputs.should_sync == 'true'
        run: |
          # 配置 Git
          git config user.name "Sync Bot"
          git config user.email "sync-bot@github.com"
          # 添加 CNB 作为远程（临时）
          git remote add cnb https://xiyingruyi:${{ secrets.CNB }}@cnb.cool/xiyingruyi/Stash-rules.git || true
          git fetch cnb
          # 尝试 merge（如果冲突，自动创建 merge commit）
          git merge cnb/main --no-ff -m "Merge CNB changes [CNB:SYNC]"
          # 如果有冲突，git 会暂停；这里用 --no-edit 跳过编辑
          # 推送到 CNB 前 commit 合并结果
          git push github main  # 先推回 GitHub（可选）
      # 原 Push 步骤保持，但去掉 force（用 PLUGIN_FORCE="false"）
      - name: Push to CNB Repository
        if: steps.check_sync.outputs.should_sync == 'true'
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/xiyingruyi/Stash-rules.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="xiyingruyi" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB }} \
            -e PLUGIN_FORCE="false" \  # 改成 false，避免覆盖
            -e PLUGIN_SYNC_MODE="push" \
            -e PLUGIN_PUSH_TAGS="true" \
            tencentcom/git-sync
