name: Update Nodes Daily

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: {}

jobs:
  update-nodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Fetch latest subscription
        run: node fetch_sub.js

      - name: Convert to YAML
        run: python node_converter.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add input_nodes.txt nodes.yaml || true
          git commit -m "Auto update nodes $(date -u +'%Y-%m-%d')" || echo "no changes"
          git push || echo "push failed"
